### PR TITLE
take the ClassLoader as an argument for ClassPathResource

### PR DESCRIPTION
**Pull request by tpolecat**
You guys are going to hate me for this, but `ClassPathResource` won't work in a managed classloading environment like OSGi. You need to take the `ClassLoader` as an argument. There is no reasonable default.

### CODE REVIEW

**Comment by stew** [comment]
without looking at what the impact in from the perspective of usability. I like this solely from the perspective that we must agree that instead of relying on some global state to take a function argument instead has got to be an improvement

**Comment by runarorama** [comment]
Looks good. How about adding a default argument of `getClass.getClassLoader`?

**Comment by tpolecat** [comment]
Yep, I can do that. The behavior right now is `anonymousClassInKnobs.getClassLoader`, and changing it to a default arg will have the behavior `classAtTheCallSite.getClassLoader`, which is probably a better default.

**Comment by runarorama** [comment]
That sounds like a good change. Will also preserve source compat.

**Comment by timperrett** [comment]
If we're breaking binary compatibility, please increment the minor version number too :-) Thanks Rob!

**Comment by tpolecat** [comment]
Actually that was a lie. The default arg is defined in its lexical scope like anything else, otherwise it would be a dynamic scoping bug. So there is no change in behavior.

**Comment by timperrett** [comment]
@tpolecat are we waiting on any more changes for this rob?

**Comment by tpolecat** [comment]
Yes, sorry. I'll finish this up today.

**Comment by tpolecat** [comment]
Ok I added a default arg for the classloader, so you can provide it if you wish, or by leaving it out you get the exact same behavior as before. Updated the minor version number to reflect this API change.

**Comment by tpolecat** [comment]
Looks like the 2.11 build isn't terminating on Travis ... might be sporadic. Works for me, heh-heh.

**Pull request merged**
