### PR TITLE
scala 2.11 support.

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by timperrett** [comment]
Whoa, @paulp this is awesome - thanks for the contribution! Travis reports an error on the java8 build, but it passes fine for me locally. Failing job is here: https://travis-ci.org/oncue/knobs/jobs/65130914

**Comment by timperrett** [comment]
Just retrying the build on Travis - https://travis-ci.org/oncue/knobs/builds/65130910

**Comment by timperrett** [comment]
After running 3 separate rounds of travis, it fails non-deterministicly (all with travis timeouts) so im happy to say its a travis issue as its not failing multiple times on the same build combination. Works perfectly well locally on every test run.

**Comment by paulp** [comment]
Travis flakiness is pretty insanity-provoking, I hope they get it under control.

**Pull request merged**
